### PR TITLE
Update gemspec and Rakefile

### PR DESCRIPTION
**Pull request by sferik**
I started off just wanting to bump the hashie version, but discovered a few other things to cleanup along the way.

Would you mind releasing a new version of the gem after merging this?

### CODE REVIEW

**Comment by tcocca** [comment]
No problem, 1 concern, do we need a dependency on rake ~> 0.9

Worried that might cause issues in apps that are running rails 2.3.x where rake 0.8.7 is used (or anything less than .9)

Thoughts?
~ Tom

**Comment by sferik** [comment]
It's just a development dependency, so it shouldn't affect any apps using rash, just developers who want to hack on rash. That said, you're welcome to relax it to ~> 0.8 if you prefer.

**Comment by tcocca** [comment]
ah, missed the dev dependency, sorry, .9 is cool, mine as well push things forward

Hopefully i'll get this merged in tonight at the bostonrb hackfest and get a new version out, i'll just do a minor version bump

**Comment by sferik** [comment]
Sounds good, man.

**Comment by tcocca** [comment]
Just released 0.3.1 to rubygems that includes this pull request (and 1 other to strip out multiple spaces in a row - issue #2)

**Pull request merged**
